services:
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: dev
    ports:
      - "50051:50051"
    volumes:
      - .:/app
    environment:
      - APP_ENV=development
